//
//  UserInteractor.swift
//  VipArchitectureDemo
//
//  Created by Sivaramaiah NAKKA on 18/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// view to interactor
protocol UserBusinessLogic {
    func viewDidLoad()
}

protocol UserDataStore {
  //var name: String { get set }
}

class UserInteractor: UserDataStore {
  var presenter: UserPresentationLogic?
  var worker: UserWorker?
}

extension UserInteractor: UserBusinessLogic {
    func viewDidLoad() {
        worker = UserWorker()
        worker?.doSomeWork()
        
        let response = User.Fetch.Response()
        presenter?.presentSomething(response: response)
      }
}
