//
//  UserPresenter.swift
//  VipArchitectureDemo
//
//  Created by Sivaramaiah NAKKA on 18/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserPresentationLogic {
  func presentSomething(response: User.Fetch.Response)
}

class UserPresenter: UserPresentationLogic {
  weak var viewController: UserDisplayLogic?
  
  func presentSomething(response: User.Fetch.Response) {
    let viewModel = User.Fetch.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
