//
//  UserPresenter.swift
//  VipArchitectureDemo
//
//  Created by Sivaramaiah NAKKA on 18/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// interactor to presentor
protocol UserPresentationLogic {
    func showUsers(with response: User.Fetch.Response)
    func showError(_ error: Error)
    func showLoader()
    func hideLoader()
}

class UserPresenter {
    // MARK: - Public
    weak var viewController: UserDisplayLogic?
}


// MARK: - Public
extension UserPresenter: UserPresentationLogic {
    func showUsers(with response: User.Fetch.Response) {
        let viewModels = buildUserViewModel(users: response.users)
        viewController?.reloadTableViewData(with: User.Fetch.ViewModel(users: viewModels))
    }
    
    func showError(_ error: Error) {
        viewController?.showError(error)
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    
    func hideLoader() {
        viewController?.hideLoader()
    }
}

// MARK: - Private
private extension UserPresenter {
    func buildUserViewModel(users: [UserModel]?) -> [UserViewModel] {
        guard let users = users  else { return [] }
        return users.map { UserViewModel(name: $0.name, website: $0.website) }
    }
}
